prowjob_namespace: default
pod_namespace: test-pods

plank:
  job_url_prefix_config:
    "*": http://prow.feast.ai/view/gcs
  report_template: '[Full PR test history](https://prow.feast.ai/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}})'
  pod_pending_timeout: 60m
  default_decoration_configs:
    "*":
      timeout: 2h
      grace_period: 15s
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20190221-d14461a
        initupload: gcr.io/k8s-prow/initupload:v20190221-d14461a
        entrypoint: gcr.io/k8s-prow/entrypoint:v20190221-d14461a
        sidecar: gcr.io/k8s-prow/sidecar:v20190221-d14461a
      gcs_configuration:
        bucket: feast-templocation-kf-feast
        path_strategy: explicit
      gcs_credentials_secret: prow-service-account

deck:
  tide_update_period: 1s
  spyglass:
    size_limit: 10e+6 # 10MB
    lenses:
    - lens:
        name: metadata
      required_files:
      - started.json|finished.json
    - lens:
        name: buildlog
      required_files:
      - build-log.txt
    - lens:
        name: junit
      required_files:
      - artifacts/.*\.xml
    - 
    # viewers:
    #   "started.json|finished.json": ["metadata"]
    #   "build-log.txt": ["buildlog"]
    #   "report.xml": ["junit"]
    #   "artifacts/.*\\.xml": ["junit"]
    #   "surefire-reports/.*\\.xml": ["junit"]

tide:
  queries:
  - repos:
    - gojek/feast
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
  merge_method:
    gojek/feast: squash
  blocker_label: merge-blocker
  squash_label: tide/squash

# presubmits and postsubmits configure ProwJobs.
# https://github.com/kubernetes/test-infra/blob/6571843b1aa7bd6cf577a7a8b9e9971241f424d5/prow/jobs.md

presubmits:
  gojek/feast:
  - name: test-core-and-ingestion
    decorate: true
    always_run: true
    spec:
      containers:
      - image: maven:3.6-jdk-8
        command: [".prow/scripts/test-core-ingestion.sh"]
        resources:
          requests:
            cpu: "1000m"
            memory: "512Mi"
          limit:
            memory: "4096Mi"

  - name: test-serving
    decorate: true
    always_run: true
    spec:
      containers:
      - image: maven:3.6-jdk-8
        command: [".prow/scripts/test-serving.sh"]

  - name: test-java-sdk
    decorate: true
    always_run: true
    spec:
      containers:
      - image: maven:3.6-jdk-8
        command: [".prow/scripts/test-java-sdk.sh"]

  - name: test-python-sdk
    decorate: true
    always_run: true
    spec:
      containers:
      - image: python:3.7
        command: [".prow/scripts/test-python-sdk.sh"]

  - name: test-golang-sdk
    decorate: true
    always_run: true
    spec:
      containers:
      - image: golang:1.13
        command: [".prow/scripts/test-golang-sdk.sh"]

  - name: test-end-to-end
    decorate: true
    always_run: true
    spec:
      containers:
      - image: maven:3.6-jdk-8
        command: [".prow/scripts/test-end-to-end.sh"]
        resources:
          requests:
            cpu: "1000m"
            memory: "1024Mi"
          limit:
            memory: "4096Mi"

  - name: test-end-to-end-batch
    decorate: true
    always_run: true
    spec:
      volumes:
      - name: service-account
        secret:
          secretName: feast-service-account
      containers:
      - image: maven:3.6-jdk-8
        command: [".prow/scripts/test-end-to-end-batch.sh"]
        resources:
          requests:
            cpu: "1000m"
            memory: "1024Mi"
          limit:
            memory: "4096Mi"
        volumeMounts:
        - name: service-account
          mountPath: "/etc/service-account"

postsubmits:
  gojek/feast:
  - name: release-automation-dry-run
    decorate: true        
    spec:
      containers:
      - image: python:3
        command:
        - |
          .prow/scripts/publish_python_sdk.sh \
            --directory_path sdk/python \
            --repository testpypi
        env:
        - name: SETUPTOOLS_SCM_PRETEND_VERSION
          value: 1.0.1
        volumeMounts:
        - name: pypirc 
          mountPath: /root/.pypirc
          subPath: .pypirc
          readOnly: true
      volumes:
      - name: pypirc
        secret:
          secretName: pypirc
    branches:
    - release-automation-dry-run
